groups:
  Material:
  - Acorn
  - Amber
  - AmberPearl
  - AncientSeed
  - Barley
  - BarleyFlour
  - BarleyWineBase
  - BeechSeeds
  - BirchSeeds
  - BlackMetal
  - BlackMetalScrap
  - Bloodbag
  - BoneFragments
  - BreadDough
  - Bronze
  - BronzeNails
  - CarrotSeeds
  - Chain
  - Chitin
  - Coal
  - Copper
  - CopperOre
  - Crystal
  - Dandelion
  - DeerHide
  - DeerMeat
  - DragonTear
  - ElderBark
  - Entrails
  - Feathers
  - FineWood
  - FirCone
  - FishRaw
  - Flametal
  - FlametalOre
  - Flax
  - Flint
  - FreezeGland
  - GreydwarfEye
  - Guck
  - HardAntler
  - Iron
  - IronNails
  - IronOre
  - IronScrap
  - JuteRed
  - LeatherScraps
  - LinenThread
  - LoxMeat
  - LoxPelt
  - LoxPieUncooked
  - MeadBaseFrostResist
  - MeadBaseHealthMedium
  - MeadBaseHealthMinor
  - MeadBasePoisonResist
  - MeadBaseStaminaMedium
  - MeadBaseStaminaMinor
  - MeadBaseTasty
  - NeckTail
  - Needle
  - Obsidian
  - OnionSeeds
  - Ooze
  - PineCone
  - QueenBee
  - RawMeat
  - Resin
  - Root
  - RoundLog
  - Ruby
  - SerpentMeat
  - SerpentScale
  - SharpeningStone
  - Silver
  - SilverNecklace
  - SilverOre
  - Stone
  - SurtlingCore
  - Tar
  - Thistle
  - Thunderstone
  - Tin
  - TinOre
  - TrollHide
  - Turnip
  - TurnipSeeds
  - VegvisirShard_Bonemass
  - WitheredBone
  - WolfClaw
  - WolfFang
  - WolfHairBundle
  - WolfMeat
  - WolfPelt
  - Wood
  - YagluthDrop
  - YmirRemains
  - ReducedWitheredBone
  Chest:
  - ArmorBronzeChest
  - ArmorFenringChest
  - ArmorIronChest
  - ArmorLeatherChest
  - ArmorPaddedCuirass
  - ArmorRagsChest
  - ArmorRootChest
  - ArmorTrollLeatherChest
  - ArmorWolfChest
  Legs:
  - ArmorBronzeLegs
  - ArmorFenringLegs
  - ArmorIronLegs
  - ArmorLeatherLegs
  - ArmorPaddedGreaves
  - ArmorRagsLegs
  - ArmorRootLegs
  - ArmorTrollLeatherLegs
  - ArmorWolfLegs
  Ammo:
  - ArrowBronze
  - ArrowFire
  - ArrowFlint
  - ArrowFrost
  - ArrowIron
  - ArrowNeedle
  - ArrowObsidian
  - ArrowPoison
  - ArrowSilver
  - ArrowWood
  - draugr_arrow
  - FishingBait
  TwoHandedWeapon:
  - AtgeirBlackmetal
  - AtgeirBronze
  - AtgeirIron
  - Battleaxe
  - BattleaxeCrystal
  - FishingRod
  - FistFenrirClaw
  - PickaxeAntler
  - PickaxeBronze
  - PickaxeIron
  - PickaxeStone
  - SledgeCheat
  - SledgeIron
  - SledgeStagbreaker
  OneHandedWeapon:
  - AxeBlackMetal
  - AxeBronze
  - AxeFlint
  - AxeIron
  - AxeStone
  - BombOoze
  - Club
  - KnifeBlackMetal
  - KnifeButcher
  - KnifeChitin
  - KnifeCopper
  - KnifeFlint
  - KnifeSilver
  - MaceBronze
  - MaceIron
  - MaceNeedle
  - MaceSilver
  - PlayerUnarmed
  - SpearBronze
  - SpearChitin
  - SpearElderbark
  - SpearFlint
  - SpearWolfFang
  - SwordBlackmetal
  - SwordBronze
  - SwordCheat
  - SwordIron
  - SwordIronFire
  - SwordSilver
  - Tankard
  - TankardAnniversary
  - TankardOdin
  Consumable:
  - BarleyWine
  - BlackSoup
  - BloodPudding
  - Blueberries
  - BoarJerky
  - Bread
  - Carrot
  - CarrotSoup
  - Cloudberry
  - CookedDeerMeat
  - CookedLoxMeat
  - CookedMeat
  - CookedWolfMeat
  - DeerStew
  - Eyescream
  - FishCooked
  - FishWraps
  - HealthUpgrade_Bonemass
  - HealthUpgrade_GDKing
  - Honey
  - LoxPie
  - MeadFrostResist
  - MeadHealthMedium
  - MeadHealthMinor
  - MeadPoisonResist
  - MeadStaminaMedium
  - MeadStaminaMinor
  - MeadTasty
  - MinceMeatSauce
  - Mushroom
  - MushroomBlue
  - MushroomYellow
  - NeckTailGrilled
  - Onion
  - OnionSoup
  - Pukeberries
  - QueensJam
  - Raspberry
  - RottenMeat
  - Sausages
  - SerpentMeatCooked
  - SerpentStew
  - ShocklateSmoothie
  - TurnipStew
  - WolfJerky
  - WolfMeatSkewer
  - CrunchyIcecream
  - MushroomBloodPudding
  - SpiderStew
  Utility:
  - BeltStrength
  - Wishbone
  Bow:
  - Bow
  - BowDraugrFang
  - BowFineWood
  - BowHuntsman
  Shoulder:
  - CapeDeerHide
  - CapeLinen
  - CapeLox
  - CapeTrollHide
  - CapeWolf
  Misc:
  - CryptKey
  - DragonEgg
  - GoblinTotem
  - SaddleLox
  - ReducedDragonEgg
  - ReducedFulingTotem
  Tool:
  - Cultivator
  - Hammer
  - Hoe
  Helmet:
  - HelmetBronze
  - HelmetDrake
  - HelmetDverger
  - HelmetFenring
  - HelmetIron
  - HelmetLeather
  - HelmetMidsummerCrown
  - HelmetOdin
  - HelmetPadded
  - HelmetRoot
  - HelmetTrollLeather
  - HelmetYule
  Shield:
  - ShieldBanded
  - ShieldBlackmetal
  - ShieldBlackmetalTower
  - ShieldBoneTower
  - ShieldBronzeBuckler
  - ShieldIronBuckler
  - ShieldIronSquare
  - ShieldIronTower
  - ShieldKnight
  - ShieldSerpentscale
  - ShieldSilver
  - ShieldWood
  - ShieldWoodTower
  Torch:
  - Torch
  Trophie:
  - TrophyAbomination
  - TrophyBlob
  - TrophyBoar
  - TrophyBonemass
  - TrophyCultist
  - TrophyDeathsquito
  - TrophyDeer
  - TrophyDragonQueen
  - TrophyDraugr
  - TrophyDraugrElite
  - TrophyDraugrFem
  - TrophyEikthyr
  - TrophyFenring
  - TrophyForestTroll
  - TrophyFrostTroll
  - TrophyGoblin
  - TrophyGoblinBrute
  - TrophyGoblinKing
  - TrophyGoblinShaman
  - TrophyGreydwarf
  - TrophyGreydwarfBrute
  - TrophyGreydwarfShaman
  - TrophyGrowth
  - TrophyHatchling
  - TrophyLeech
  - TrophyLox
  - TrophyNeck
  - TrophySerpent
  - TrophySGolem
  - TrophySkeleton
  - TrophySkeletonPoison
  - TrophySurtling
  - TrophyTheElder
  - TrophyUlv
  - TrophyWolf
  - TrophyWraith
  Trophie_MonsterLabZ:
  - TrophyDeepSeaSerpent
  - TrophyMolluscan
  - TrophyDeepSeaMolluscan
  - TrophyNightmareDragon
  - TrophySurtr
  Material_MonsterLabZ:
  - SuccubusTail
  - SpiderFang
  Chest_ChaosArmor:
  - T0ChaosPlateArmor
  - T1ChaosPlateArmor
  - T2ChaosPlateArmor
  - ChaosPlateArmorBody
  - EliteChaosPlateArmor
  Helmet_ChaosArmor:
  - T0ChaosPlateHelm
  - T1ChaosPlateHelm
  - T2ChaosPlateHelm
  - ChaosPlateHelm
  - EliteChaosPlateHelm
  - ChaosPlateHelmAlt
  Legs_ChaosArmor:
  - T0ChaosPlateLegs
  - T1ChaosPlateLegs
  - T2ChaosPlateLegs
  - ChaosPlateLegs
  - EliteChaosPlateLegs
  Material_Warfare:
  - RuneBer_TW
  - RuneAlgiz_TW
  - RuneDagaz_TW
  - RuneEihwaz_TW
  - RuneFehu_TW
  - RuneJara_TW
  - RuneMannaz_TW
  - RuneOthala_TW
  - RunePerth_TW
  - RuneRaidho_TW
  - RuneThurisaz_TW
  - FreyjaEssence_TW
  - AshenScale_TW
  - AshenFur_TW
  - AshenFang_TW
  - AshenClaw_TW
  - SmolderingCore_TW
  - ScorchedFragments_TW
  - LavaGem_TW
  - VolcanicStone_TW
  - JotunnTooth_TW
  - ArcticLoxPelt_TW
  - ArcticWolfPelt_TW
  - ArcticSerpentScale_TW
  - FrozenFang_TW
  - FrozenClaw_TW
  - FrozenOrb_TW
  - FrozenFragments_TW
  - QueenJewel_TW
  - AncientHeart_TW
  - DarkCrystal_TW
  - VenomousFang_TW
  - ArachnidSilk_TW
  - ArachnidOoze_TW
  - SvartalfrEye_TW
  - SvartalfrFabric_TW
  - SvartalfrArtifact_TW
  - GoblinScraps_TW
  - LoxBone_TW
  - RottenPelt_TW
  - TrollBone_TW
  - Sapphire_TW
  - Emerald_TW
  - Amethyst_TW
  - Topaz_TW
  - Onyx_TW
  Helmet_Warfare:
  - HelmetRotten_TW
  - HelmetLox_TW
  - HelmetUllr_TW
  Chest_Warfare:
  - ArmorRottenChest_TW
  - ArmorLoxChest_TW
  - ArmorUllrChest_TW
  Legs_Warfare:
  - ArmorRottenLegs_TW
  - ArmorLoxLegs_TW
  - ArmorUllrLegs_TW
  Shoulder_Warfare:
  - CapeRotten_TW
  - CapeArcticLox_TW
  - CapeArcticWolf_TW
  - CapeAshenScale_TW
  Ammo_Warfare:
  - ArrowBone_TW
  - ArrowPickaxe_TW
  - ArrowFrometal_TW
  - ArrowFlametal_TW
  - ArrowExplosiveFire_TW
  - ArrowExplosiveFrost_TW
  - ArrowExplosiveLightning_TW
  - ArrowExplosivePoison_TW
  OneHandedWeapon_Warfare:
  - AxeSilver_TW
  - AxeNjord_TW
  - AxeSurtr_TW
  - KnifeIron_TW
  - KnifeWrench_TW
  - KnifeNjord_TW
  - KnifeSurtr_TW
  - MaceNjord_TW
  - MaceSurtr_TW
  - SpearBlackmetal_TW
  - SpearNjord_TW
  - SpearSurtr_TW
  - SwordScimitar_TW
  - SwordChitin_TW
  - SwordNjord_TW
  - SwordSurtr_TW
  TwoHandedWeapon_Warfare:
  - AtgeirSilver_TW
  - AtgeirNjord_TW
  - AtgeirSurtr_TW
  - TridentBlackmetal_TW
  - BattleaxeBronze_TW
  - BattleaxeIron_TW
  - BattleaxeSilver_TW
  - BattleaxeBlackmetal_TW
  - BattleaxeNjord_TW
  - BattleaxeSurtr_TW
  - BattlehammerIron_TW
  - BattlehammerSilver_TW
  - BattlehammerBlackmetal_TW
  - BattlehammerHeavymetal_TW
  - BattlehammerSurtr_TW
  - BattlehammerAesir_TW
  - BattlehammerNjord_TW
  - ClaymoreBronze_TW
  - ClaymoreChitin_TW
  - ClaymoreIron_TW
  - ClaymoreSilver_TW
  - ClaymoreBlackmetal_TW
  - ClaymoreColussus_TW
  - ClaymoreJotunn_TW
  - ClaymoreNjord_TW
  - ClaymoreSurtr_TW
  - FistSilver_TW
  - FistBlackmetal_TW
  - FistHeavymetal_TW
  - FistNjord_TW
  - FistSurtr_TW
  - GreatClub_TW
  - SledgeTrollbone_TW
  - SledgeSilver_TW
  - SledgeBlackmetal_TW
  - SledgeNjord_TW
  - SledgeSurtr_TW
  - PickaxeSilver_TW
  - PickaxeBlackmetal_TW
  Bow_Warfare:
  - BowBlackmetal_TW
  - GreatbowBlackmetal_TW
  - BowUllr_TW
  - BowNjord_TW
  - BowSurtr_TW
  - GreatbowNjord_TW
  Shield_Warfare:
  - ShieldNjordTower_TW
  - ShieldSurtrTower_TW
  - ShieldNjord_TW
  - ShieldSurtr_TW
  - ShieldHeavymetalBuckler_TW
  - ShieldFrometalBuckler_TW
  - ShieldFlametalBuckler_TW
  Material_RareMagicPortal:
  - PortalMagicFluid
  - PortalCrystalMaster
  - PortalCrystalRed
  - PortalCrystalGreen
  - PortalCrystalBlue
  - PortalCrystalPurple
  - PortalCrystalTan
  Consumable_RareMagicPortal:
  - PortalDrink
  Misc_RareMagicPortal:
  - PortalKeyRed
  - PortalKeyGold
  - PortalKeyBlue
  - PortalKeyGreen
  - PortalKeyPurple
  - PortalKeyTan
  Material_Epic_Loot:
  - RunestoneMagic
  - RunestoneRare
  - RunestoneEpic
  - RunestoneLegendary
  - ShardMagic
  - ShardRare
  - ShardEpic
  - ShardLegendary
  - DustMagic
  - DustRare
  - DustEpic
  - DustLegendary
  - ReagentMagic
  - ReagentRare
  - ReagentEpic
  - ReagentLegendary
  - EssenceMagic
  - EssenceRare
  - EssenceEpic
  - EssenceLegendary
  Utility_Epic_Loot:
  - LeatherBelt
  - SilverRing
  - GoldRubyRing
  - Andvaranaut
  Misc_Epic_Loot:
  - ForestToken
  - IronBountyToken
  - GoldBountyToken
  Tool_Clutter:
  - $PlumgaClutterTool
  Consumable_DoOrDieMonsters:
  - CarnivorBait_DoD
  Trophie_DoOrDieMonsters:
  - TrophyCharredRemains_DoD
  - TrophyFrozenBones_DoD
  - TrophyGreatSurtling_DoD
  - TrophySkeletonG_DoD
  - TrophySkeletonR_DoD
  - TrophyFrostling_DoD
  - TrophyStormling_DoD
  - TrophyVoidling_DoD
  - TrophyOGolem_DoD
  - TrophyLGolem_DoD
  - TrophyIceGolem_DoD
  - TrophyVilefang_DoD
  - TrophyDireWolf_DoD
  - TrophyForestWolf_DoD
  - TrophyLivingLava_DoD
  - TrophyLivingWater_DoD
  - TrophyBlackDeer_DoD
  - TrophyIceDrake_DoD
  - TrophyFlameDrake_DoD
  - TrophyArcaneDrake_DoD
  - TrophyDarknessDrake_DoD
  - TrophyGoldDrake_DoD
  - TrophyPoisonDrake_DoD
  - TrophyDarkDrake_DoD
  Material_DoOrDieMonsters:
  - InfusedGemstone_DoD
  - BoarTusk_DoD
  - LargeFang_DoD
  - ShamansVessel_DoD
  - GreydwarfHeart_DoD
  - SkeletonBones_DoD
  - GreyPearl_DoD
  - FrozenBone_DoD
  - CharredBone_DoD
  - FrostlingCore_DoD
  - StormlingCore_DoD
  - VoidlingCore_DoD
  - ForestWolfPelt_DoD
  - DireWolfPelt_DoD
  - WaterGlobe_DoD
  - SpiderChitin_DoD
  - BlackDeerHide_DoD
  - SkullToken_DoD
  Material_Epic_Valheims_Additions_by_Huntard:
  - HeavymetalBar
  - FrometalBar
  - DeepAbyssEssence
  - Heavyscale
  - Drakescale
  - Forgedscale
  - OreHeavymetal
  - OreFrometal
  - FrostInfusedDarkMetal
  - BurningWorldTreeFragment
  - PrimordialIce
  Trophie_Epic_Valheims_Additions_by_Huntard:
  - CursedEffigy
  - TrophySvartalfarQueen
  - TrophyJotunn
  - TrophyHelDemon
  None_Epic_Valheims_Additions_by_Huntard:
  - WorldTreeFragment
  - FenrirsHeart
  - YmirsSoulEssence
  TwoHandedWeapon_Epic_Valheims_Additions_by_Huntard:
  - AtgeirHeavymetal
  - SledgeHeavymetal
  - BattleaxeHeavymetal
  - GreatSwordHeavymetal
  - PickaxeHeavymetal
  - AtgeirFrometal
  - SledgeFrometal
  - BattleaxeFrometal
  - GreatSwordFrometal
  - PickaxeFrometal
  - AtgeirFlametal
  - SledgeFlametal
  - BattleaxeFlametal
  - GreatSwordFlametal
  - PickaxeFlametal
  - TridentDeepAbyss
  - GreatSwordDeepAbyss
  Bow_Epic_Valheims_Additions_by_Huntard:
  - BowHeavymetal
  - BowFrometal
  - BowFlametal
  - BowDeepAbyss
  OneHandedWeapon_Epic_Valheims_Additions_by_Huntard:
  - SpearHeavymetal
  - KnifeHeavymetal
  - MaceHeavymetal
  - SwordHeavymetal
  - AxeHeavymetal
  - SpearFrometal
  - KnifeFrometal
  - MaceFrometal
  - SwordFrometal
  - AxeFrometal
  - SpearFlametal
  - KnifeFlametal
  - MaceFlametal
  - SwordFlametal
  - AxeFlametal
  Shield_Epic_Valheims_Additions_by_Huntard:
  - ShieldHeavymetal
  - ShieldHeavymetalTower
  - ShieldFrometal
  - ShieldFrometalTower
  - ShieldFlametal
  - ShieldFlametalTower
  Helmet_JudesEquipment:
  - ArmorNobleHelmet
  - ArmorBarbarianBronzeHelmetJD
  - ArmorWarriorHelmet
  - ArmorPlateIronHelmetJD
  - ArmorDragonslayerHelmet
  - ArmorWandererHelmet
  - ArmorBlackmetalgarbHelmet
  - ArmorSerpentHelmet
  - ArmorMistlandsHelmet
  Chest_JudesEquipment:
  - ArmorNobleChest
  - ArmorBarbarianBronzeChestJD
  - ArmorWarriorChest
  - ArmorPlateIronChestJD
  - ArmorDragonslayerChest
  - ArmorWandererChest
  - ArmorBlackmetalgarbChest
  - ArmorSerpentChest
  - ArmorMistlandsChest
  Legs_JudesEquipment:
  - ArmorNobleLegs
  - ArmorBarbarianBronzeLegsJD
  - ArmorWarriorLegs
  - ArmorPlateIronLegsJD
  - ArmorDragonslayerLegs
  - ArmorWandererLegs
  - ArmorBlackmetalgarbLegs
  - ArmorSerpentLegs
  - ArmorMistlandsLegs
  Shoulder_JudesEquipment:
  - ArmorNobleCape
  - ArmorBarbarianCapeJD
  - ArmorPlateCape
  - ArmorWandererCape
  - ArmorSerpentCape
  - BackpackSimple
  - BackpackHeavy
  Woods:
   - Wood
   - FineWood
   - RoundLog
   - ElderBark
#
all:
    floating: yes
    pickup: yes
# stuff floats in water; everything is pickable

Woods:
  amount:
    2: 1.1
    3: 1.2
    4: 1.3
    5: 1.4
# increased Wood after World Level 3

DragonEgg:
    stack: 3
    weight: 100
# dragon eggs stack up to 3, and weigh considerably less

Metal:
    teleportable: no
Ore:
    teleportable: no
# ores are not teleportable

Food:
    loss: no
Thunderstone:
    loss: no
PortalDrink:
    loss: no

# This will make you keep certain items in your inventory, if you happen to die.

Coins:
    stack: 2000
    weight: 0.05
# make coins lighter